# Generated by Django 5.2.8 on 2026-01-05 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0001_initial'),
        ('recruitment', '0005_vacancysocialpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('last_checkpoint', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused_no_credits', 'Paused (No Credits)'), ('error', 'Error'), ('completed', 'Completed')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_thread', to='recruitment.application', verbose_name='Postulación')),
            ],
        ),
    ]
