# Generated by Django 5.2.8 on 2025-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('screening', 'En Screening'), ('interview', 'En Entrevista'), ('offer', 'Oferta Enviada'), ('hired', 'Contratado'), ('rejected', 'Rechazado'), ('withdrawn', 'Retirado')], default='new', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(choices=[('linkedin', 'LinkedIn'), ('website', 'Sitio Web'), ('referral', 'Referido'), ('agency', 'Agencia'), ('other', 'Otro')], default='website', max_length=20, verbose_name='Fuente')),
                ('score', models.FloatField(default=0.0, help_text='Puntaje de evaluación (0-100)', verbose_name='Puntaje')),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Postulación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('resume_url', models.URLField(blank=True, help_text='URL del archivo del CV', verbose_name='CV URL')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Lista de habilidades extraídas o manuales', verbose_name='Habilidades')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Puesto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requirements', models.TextField(help_text='Lista de requisitos técnicos y habilidades blandas', verbose_name='Requisitos')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='Estado')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario Mínimo')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Salario Máximo')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Remoto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
            ],
            options={
                'verbose_name': 'Vacante',
                'verbose_name_plural': 'Vacantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
