# Generated by Django 5.2.8 on 2025-11-27 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobvacancy', verbose_name='Vacante'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'email'], name='recruitment_tenant__4d74d8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['tenant', 'last_name'], name='recruitment_tenant__dc125d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('tenant', 'email')},
        ),
        migrations.AddIndex(
            model_name='jobvacancy',
            index=models.Index(fields=['tenant', 'status'], name='recruitment_tenant__794af8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['tenant', 'status'], name='recruitment_tenant__7cc0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['vacancy', 'status'], name='recruitment_vacancy_57ca44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('vacancy', 'candidate')},
        ),
    ]
