# Generated by Django 6.0 on 2025-12-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvacancy',
            name='interview_mode',
            field=models.CharField(choices=[('auto', 'Entrevista por IA'), ('manual', 'Entrevista Manual (Humano)')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='manual_interview_guide',
            field=models.TextField(blank=True, null=True),
        ),
    ]
