# Generated by Django 5.2.8 on 2025-12-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_jobvacancy_interview_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20, verbose_name='Plataforma')),
                ('content', models.TextField(help_text='Contenido personalizable para esta red social específico.', verbose_name='Contenido del Post')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('published', 'Publicada'), ('failed', 'Fallida')], default='draft', max_length=20, verbose_name='Estado')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='recruitment.jobvacancy', verbose_name='Vacante')),
            ],
            options={
                'verbose_name': 'Publicación en Red Social',
                'verbose_name_plural': 'Publicaciones en Redes Sociales',
                'unique_together': {('vacancy', 'platform')},
            },
        ),
    ]
