# Generated by Django 5.2.8 on 2026-01-12 12:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_vacancysocialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancysocialpost',
            name='edited_content',
            field=models.TextField(blank=True, help_text='Contenido editado por el usuario (sobrescribe el generado)', null=True, verbose_name='Contenido Editado'),
        ),
        migrations.AddField(
            model_name='vacancysocialpost',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Cuándo se generó el contenido con IA', verbose_name='Fecha de Generación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancysocialpost',
            name='manually_published_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo el usuario marcó como publicado manualmente', null=True, verbose_name='Fecha de Publicación Manual'),
        ),
    ]
