"""Serializer para VacancySocialPost."""

from rest_framework import serializers

from apps.recruitment.models import VacancySocialPost


class VacancySocialPostSerializer(serializers.ModelSerializer):
    """Serializer para el modelo VacancySocialPost."""

    status_display = serializers.CharField(
        source="get_status_display", read_only=True
    )
    platform_display = serializers.CharField(
        source="get_platform_display", read_only=True
    )
    final_content = serializers.SerializerMethodField(read_only=True)

    class Meta:
        model = VacancySocialPost
        fields = [
            "id",
            "vacancy",
            "platform",
            "platform_display",
            "content",
            "edited_content",
            "final_content",
            "status",
            "status_display",
            "posted_at",
            "generated_at",
            "manually_published_at",
            "created_at",
            "updated_at",
        ]
        read_only_fields = [
            "id",
            "vacancy",
            "platform",
            "content",  # Generated by AI, not editable directly
            "status",  # Controlled by system actions
            "posted_at",
            "generated_at",
            "manually_published_at",
            "created_at",
            "updated_at",
        ]

    def get_final_content(self, obj: VacancySocialPost) -> str:
        """Retorna el contenido final (editado o generado)."""
        return obj.get_final_content()

    def validate_edited_content(self, value: str | None) -> str | None:
        """Valida el contenido editado."""
        if value and len(value.strip()) == 0:
            raise serializers.ValidationError(
                "El contenido editado no puede estar vacío."
            )
        return value

