# Generated by Django 5.2.8 on 2025-11-27 11:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre legal o comercial de la empresa', max_length=255, verbose_name='Nombre de la Empresa')),
                ('slug', models.SlugField(help_text='Identificador único para URLs (ej: empresa-abc)', max_length=255, unique=True, verbose_name='Slug')),
                ('plan', models.CharField(choices=[('basic', 'Básico'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', help_text='Plan de suscripción del tenant', max_length=20, verbose_name='Plan Actual')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el tenant está activo', verbose_name='Activo')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Número máximo de usuarios permitidos', verbose_name='Máximo de Usuarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Miembro')], default='member', help_text='Rol del usuario dentro del tenant', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la membresía está activa', verbose_name='Activo')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Membresía de Tenant',
                'verbose_name_plural': 'Membresías de Tenant',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('llama', 'Meta Llama')], default='openai', help_text='Proveedor de IA a utilizar', max_length=20, verbose_name='Proveedor de IA')),
                ('api_key', models.CharField(help_text='API Key del proveedor (será encriptada)', max_length=500, verbose_name='API Key')),
                ('model_name', models.CharField(default='gpt-4', help_text='Modelo específico a usar (ej: gpt-4, claude-3)', max_length=100, verbose_name='Nombre del Modelo')),
                ('temperature', models.FloatField(default=0.7, help_text='Controla la creatividad (0.0 - 2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)], verbose_name='Temperatura')),
                ('max_tokens', models.PositiveIntegerField(default=2000, help_text='Máximo de tokens por request', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Máximo de Tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la configuración está activa', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuraciones de IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
