# Generated by Django 5.2.8 on 2025-11-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantaiconfig',
            name='provider',
            field=models.CharField(choices=[('platform_default', 'Default de la Plataforma'), ('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('llama', 'Meta Llama')], default='openai', help_text='Proveedor de IA a utilizar', max_length=20, verbose_name='Proveedor de IA'),
        ),
    ]
