# Generated by Django 5.2.8 on 2025-12-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenantaiconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dueño'), ('admin', 'Administrador'), ('member', 'Miembro')], default='member', help_text='Rol del usuario dentro del tenant', max_length=20, verbose_name='Rol'),
        ),
    ]
