# Generated by Django 5.2.8 on 2025-12-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_logo_tenant_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantaiconfig',
            name='provider',
            field=models.CharField(choices=[('platform_default', 'Default de la Plataforma'), ('openai', 'OpenAI'), ('claude', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('llama', 'Meta Llama')], default='openai', help_text='Proveedor de IA a utilizar', max_length=20, verbose_name='Proveedor de IA'),
        ),
    ]
