# Generated by Django 5.2.8 on 2025-12-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantaiconfig_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list, help_text='Lista de permisos específicos otorgados a este miembro.', verbose_name='Permisos Adicionales'),
        ),
    ]
